### PR TITLE
[#178124702] Structure output files for dandi

### PR DESCRIPTION
**Pull request by dsleiter**
https://www.pivotaltracker.com/story/show/178124702

Dandisets seem to follow the directory structure of BIDS but without the metadata files. However, they usually have the nwb files directly in the subject directories instead of a nested `nirs` directory. So that is the file structure I copied here.

The output dataset should have the following structure:
```
├── sub-01
│   └── sub-01_task-tapping_nirs.nwb
├── sub-02
│   └── sub-02_task-tapping_nirs.nwb
├── sub-03
│   └── sub-03_task-tapping_nirs.nwb
├── sub-04
│   └── sub-04_task-tapping_nirs.nwb
└── sub-05
    └── sub-05_task-tapping_nirs.nwb
```

A required OUTPUT_PATH argument was added to the script and the documentation was updated.

Note: we decided to take unit tests oos for now, but they will be added here: https://www.pivotaltracker.com/story/show/178536860

### CODE REVIEW

**Comment by dsleiter** [comment]
@sumner15 and @ecooper2: please hold off on reviewing until #2 is merged in (this PR is dependent on that one so I branched off the tip of that PR, which means that the diff for this PR includes changes from that PR).

**Comment by dsleiter** [comment]
@sumner15 @ecooper2 this one is ready for review!

**Review by ecooper2 — APPROVED** [review]
This seems like a positive step to me - is there any example of the files themselves?  Or can I safely conclude this PR only addresses the output directory structure into which these files are directed, rather than changing those files themselves?

**Comment by dsleiter** [comment]
@ecooper2 I think you should test it out! You can clone the repo and follow the README instructions. It would be a good test of whether or not the README instructions are complete!

**Review by sumner15 — APPROVED** [review]
```bash
converting SNIRF --> NWB:
  data/BIDS-NIRS-Tapping/sub-01/nirs/sub-01_task-tapping_nirs.snirf --> data/dandiset/sub-01/sub-01_task-tapping_nirs.nwb
converting SNIRF --> NWB:
  data/BIDS-NIRS-Tapping/sub-02/nirs/sub-02_task-tapping_nirs.snirf --> data/dandiset/sub-02/sub-02_task-tapping_nirs.nwb
converting SNIRF --> NWB:
  data/BIDS-NIRS-Tapping/sub-03/nirs/sub-03_task-tapping_nirs.snirf --> data/dandiset/sub-03/sub-03_task-tapping_nirs.nwb
converting SNIRF --> NWB:
  data/BIDS-NIRS-Tapping/sub-04/nirs/sub-04_task-tapping_nirs.snirf --> data/dandiset/sub-04/sub-04_task-tapping_nirs.nwb
converting SNIRF --> NWB:
  data/BIDS-NIRS-Tapping/sub-05/nirs/sub-05_task-tapping_nirs.snirf --> data/dandiset/sub-05/sub-05_task-tapping_nirs.nwb

Conversion successful!
```

It's beautiful  😄

**Pull request merged**
